
sonar.projectKey=thekyria_theblas
sonar.organization=thekyria

sonar.projectName=theblas
sonar.projectVersion=0.1.0

sonar.sources=src,include
sonar.tests=tests

sonar.scm.provider=git

# Compilation database produced by CMake (CMAKE_EXPORT_COMPILE_COMMANDS=ON)
sonar.cfamily.compile-commands=build/compile_commands.json
