name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build and test (wrapper for CMake)
      run: make test

    - name: Create documentation (wrapper for doxygen)
      run: make docs
